
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
<<<<<<< HEAD
  replicas: 3
=======
  replicas: 2
>>>>>>> 795f45f7cba95fd56ef474d006c9cf9a47fad30a
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
